package com.Ivan.Rwalent.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "notifications")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recipient_user_id", nullable = false)
    private User recipient; // The user who should receive this notification

    @Column(nullable = false, length = 500)
    private String message;

    @Column(length = 50)
    private String notificationType; // e.g., "BOOKING_REQUEST", "BOOKING_APPROVED", "BOOKING_REJECTED"

    private Long relatedBookingId; // Optional: ID of the booking this notification relates to

    private String relatedUserName; // Optional: Name of the user/talent involved in the event

    @Column(nullable = false)
    private boolean isRead = false;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // Constructor, Getters, and Setters will be generated by Lombok
} 